version: "3.7"

services:
    nginx:
        container_name: app-nginx
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static-html:/usr/share/nginx/html
        ports:
            - "80:80"
        
        depends_on:
            - node-app
            - sample-app
        networks:
            - appnet
    mysql-db:
        image: mysql/mysql-server
        container_name: mysql-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
            - "./data:/var/lib/mysql:rw"
        ports:
            - "3308:3306"
        expose:
            - "3306"
        networks:
            - appnet
    node-app:
        container_name: node-app
        ports:
            - "3030:3030"
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - "./server:/usr/src/server"
            - "./server/node_modules:/usr/src/server/node_modules"
        environment:
            - NODE_ENV=${NODE_ENV}
        networks:
            - appnet
    sample-app:
        container_name: sample-app
        build:
            context: ./client_rc
            dockerfile: Dockerfile
        volumes:
            - "./client_rc/app:/usr/src/app"
            - "./client_rc/app/node_modules:/usr/src/app/node_modules"
        ports:
            - "3000:3000"
        expose:
            - "3000"
        environment:
            - "API_URL=https://production.example.com"
        
        environment:
            - NODE_ENV=${NODE_ENV}
            - CHOKIDAR_USEPOLLING=true
        networks:
            - appnet

volumes:
    db_data:
networks:
    appnet:
        driver: "bridge"
